### ISSUE TITLE
it's time to upgrade to jdk8

### ISSUE THREAD

**Issue by ensean** [bibinwilson/jenkins-docker-slave#1]
From my testing, it seems that jdk7 is not compatible with jenkins 2.73.2 + docker plugin 1.0.2, maybe it's time to update to jkd 8?

**Comment by prawen** [comment]
Dont you think ubuntu image you pulling is so big ?

**Comment by bibinwilson** [comment]
@prawen please raise a pull request if you have the latest image configs for the same,

**Comment by bibinwilson** [comment]
fixed
